name: ci-linux
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-cabal
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIX_CONFIG: accept-flake-config = true
    steps:
      # install deps.
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/local/share/chromium || true
          sudo apt-get clean
          sudo nix-collect-garbage -d || true
          df -h

      - name: Install system dependencies
        uses: input-output-hk/actions/base@latest

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            accept-flake-config = true

      - uses: actions/checkout@v4

      - name: Cache .cabal
        uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: cabal-${{ hashFiles('cabal.project') }}

      - name: Prepare dependencies and build environment
        run: |
          nix develop .#ghc966-nohoogle -c bash -lc 'ghc --version'
          nix develop .#ghc966-nohoogle -c bash -lc 'cabal update'

      - name: Build
        run: |
          nix develop .#ghc966-nohoogle -c bash -lc 'cabal build --ghc-options=-Werror -j all'

      - name: Test
        run: |
          nix develop .#ghc966-nohoogle -c bash -lc 'cabal test --ghc-options=-Werror all'
